import localFont from "next/font/local";
import { UserProvider } from './userContext.js';
import { ProtectedRoutes } from "./protectedRoutes.js";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Wrap the whole app with UserProvider */}
        <UserProvider>
          <ProtectedRoutes>
          {/* Conditionally protect routes if needed */}
            {children}
            </ProtectedRoutes>
        </UserProvider>
      </body>
    </html>
  );
}
